### PR TITLE
Export `krr`, fix tests

### PR DESCRIPTION
**Pull request by JeffFessler**
and more use of `using` to help reader (e.g., me) know what is used where.

### CODE REVIEW

**Comment by JeffFessler** [comment]
In cases where the error in v1.7 was similar, I just replaced with with the new error.
In cases where the new error was noticeably bigger, I left the old error in as a comment in case you want to check.
The test values work with v1.7 (not even v1.6, to my surprise) so I bumped the julia version to 1.7.

**Comment by StevenWhitaker** [comment]
I had wanted to incorporate StableRNGs.jl into the tests, so thanks for making a PR to motivate me to do that :)

I'll just merge this PR after CI finishes.

**Comment by JeffFessler** [comment]
Having to put `rng` as an arg in many places seems inconvenient for user and maybe is a lot of breaking changes.
Using a named kwarg with a sensible default` ; rng = Random.GLOBAL_RNG` would be more appealing to me.

The values I put in there are for julia 1.7 so I don't know if they work with 1.6.
But why "Julia 1" fails is baffling.

**Comment by StevenWhitaker** [comment]
I agree; `rng = Random.GLOBAL_RNG` is the default (just not a kwarg). (I try to avoid kwargs because they don't participate in dispatch, so I think it at least slightly affects performance.) So there shouldn't be any breaking changes.

I should have clarified: when I added StableRNGs, I also changes all the comparison values (overwriting the changes you made). So the tests pass locally for me for both v1.6.5 and v1.7.1, so I'm not sure why they fail on CI.

**Comment by StevenWhitaker** [comment]
I'm just going to merge this and then try to figure out the CI issues separately.

**Pull request merged**
